---
  - hosts: localhost
    vars:
      appName: "webapp"
    become: true
    tasks:
    - name: clean the workspace
      command: "{{ item }}"
      with_items:
        - "rm -rf *"
        - "rm -f *"
      args:
        chdir: "/home/ansadmin/jenkins/{{ appName }}/workspace"
    - name: building docker image
      command: "docker build -t {{ appName }} ."
      args:
        chdir: "/home/ansadmin/jenkins/{{ appName }}/workspace"
    - name: tag docker image
      command: "docker tag {{ appName }} {{ tag }}"
    - name: push the name to registry
      command: "docker push {{ tag }}"
    - name: cleaning
      command: "{{ item }}"
      with_items:
       - "rm -f *"
       - "rm -rf *"
       - "docker rmi {{ appName }} {{ tag }}"
       - "docker system prune -f -a"
      args:
        chdir: "/home/ansadmin/jenkins/{{ appName }}/workspace"
      ignore_errors: yes
  
